# Group 3's Docker Compose YAML file for the mySQL Database

name: register-r-us
services:
  rru_database:
    container_name: rru_database
    image: mysql
    restart: always
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 20s
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - rru_network

  # Spring boot server
  backend:
    build: ./backend
    container_name: rru_backend
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      rru_database:
        condition: service_healthy
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_URL: ${DB_URL}
      SERVER_PORT: ${SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      CLIENT_URL: ${CLIENT_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - rru_network

  # React frontend
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:${SERVER_PORT}/api
    container_name: rru_frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - rru_network

# Define a custom bridge network
networks:
  rru_network:
    driver: bridge
